name: quent
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.5.4
  equatable: ^2.0.8
  
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.3
  pinput: ^6.0.2
  bloc: ^9.2.0
  dio: ^5.9.1
  flutter_secure_storage: ^10.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  get_it: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0


flutter:

  
  uses-material-design: true


  assets:
    - assets/images/icons/
    - assets/images/splash/
    - assets/images/on_boarding/
    - assets/images/logo/

    - lib/l10n/intl_ar.arb
    - lib/l10n/intl_en.arb

  
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito/Nunito-Light.ttf
          weight: 300
    - family: Alexandria
      fonts:
        - asset: assets/fonts/Alexandria/Alexandria-Bold.ttf
          weight: 700
        - asset: assets/fonts/Alexandria/Alexandria-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Alexandria/Alexandria-Medium.ttf
          weight: 500
        - asset: assets/fonts/Alexandria/Alexandria-Regular.ttf
          weight: 400
flutter_intl:
  enabled: true
